---
- name: Install package dependencies.
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl

- name: install zsh and friends
  become: true
  become_user: root
  package: name={{ item }}
  with_items:
    - git-core
    - powerline
    - zsh

- name: Check the shell of "{{ lookup('env', 'USER') }}"
  changed_when: false
  ansible.builtin.shell:
    cmd: "getent passwd {{ lookup('env', 'USER') }} | cut -d: -f7"
  register: user_shell_result

- name: change user shell to zsh
  become: true
  become_user: root
  command: chsh -s /bin/zsh {{ lookup('env', 'USER') }}
  when: "'/bin/zsh' not in user_shell_result.stdout"

- name: Check for oh-my-zsh
  stat: path=/$HOME/.oh-my-zsh
  register: ohmyzsh

- name: install oh-my-zsh
  shell: bash -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  when: not ohmyzsh.stat.exists

- name: Check for dircolors
  stat: path=/$HOME/.dircolors
  register: dircolors

- name: Install dircolors
  get_url: url=https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.ansi-dark dest=/$HOME/.dircolors
  when: not dircolors.stat.exists

- name: Check for powerlevel10k
  stat:
    path: /$HOME/.oh-my-zsh/custom/themes/powerlevel10k
  register: powerlevel10k

- name: Check for powerlevel10k variable
  ansible.builtin.debug:
    msg: "Variable powerlevel10k contains: {{ powerlevel10k }}"

- name: Clone powerlevel10k
  command: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $HOME/.oh-my-zsh/custom/themes/powerlevel10k
  when: not powerlevel10k.stat.exists
  # ignore_errors: true

- name: Check if ~/.dircolors contains "DIR 34"
  shell: "grep -q 'DIR 34' ~/.dircolors"
  register: grep_result   # if the string is found, the return code is 0
  changed_when: false
  ignore_errors: true   # return code after the first run will be 1, thus ignore_errors for mutliple runs
  failed_when: grep_result.rc == 2  # Set this condition to handle the absence of "DIR 34"

- name: Update ~/.dircolors to not have dark blue directories
  ansible.builtin.lineinfile:
    path: ~/.dircolors
    regexp: '^DIR 34'
    line: 'DIR 36'
  when: grep_result.rc == 0

- name: Check if ~/.zshrc exists
  stat:
    path: ~/.zshrc
  register: zshrc_file

- name: Add snapd binary path to ~/.zshrc
  lineinfile:
    path: ~/.zshrc
    line: 'export PATH=$PATH:/snap/bin'
    # create: true
    state: present
  when: zshrc_file.stat.exists
