---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Update apt cache (on Debian).
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

- ansible.builtin.import_playbook: ../../playbook.yaml
