# source: https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt
# Avoid apt-key due to deprecation: https://www.jeffgeerling.com/blog/2022/aptkey-deprecated-debianubuntu-how-fix-ansible
# Note: recommended keyring location is /etc/apt/keyrings/ according to man 5 sources.list
---
- name: Install package dependencies.
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ca-certificates
    - curl
    - lsb-release
    - gnupg
    - apt-transport-https

- name: Add an apt signing key for azure-cli
  become: true
  changed_when: false
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings/microsoft.asc
    mode: '0644'
    force: true

- name: Add the key to the apt keyring
  become: true
  ansible.builtin.command: |
    gpg --dearmor -o /etc/apt/keyrings/microsoft.gpg /etc/apt/keyrings/microsoft.asc
  args:
    creates: /etc/apt/keyrings/microsoft.gpg

- name: Get az_dist variable
  ansible.builtin.command: lsb_release -cs
  register: az_dist_output
  changed_when: false

- name: Set az_dist fact
  set_fact:
    az_dist: "{{ az_dist_output.stdout }}"
  when: az_dist_output.stdout is defined

- name: Add apt repository for stable version
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ {{ az_dist }} main"
    state: present

- name: Install azure-cli
  become: true
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - azure-cli

# Nice try microsoft ;)
# - name: Install azure cli
#   become: true
#   command: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
