# source: https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt
---
- name: Install package dependencies.
  become: true
  package: name={{ item }} state=present
  with_items:
    - ca-certificates
    - curl
    - lsb-release
    - gnupg
    - apt-transport-https

- name: Add an apt signing key for azure-cli
  become: true
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Get AZ_DIST variable
  shell: lsb_release -cs
  register: az_dist_output
  changed_when: false

- name: Set AZ_DIST fact
  set_fact:
    AZ_DIST: "{{ az_dist_output.stdout }}"
  when: az_dist_output.stdout is defined

- name: Add apt repository for stable version
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ AZ_DIST }} main
    state: present

- name: Install azure-cli
  become: true
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - azure-cli

# Nice try microsoft ;)
# - name: Install azure cli
#   become: true
#   command: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
