---
- name: Download butane tool 
  ansible.builtin.get_url:
    url:  https://mirror.openshift.com/pub/openshift-v4/clients/butane/latest/butane-amd64
    dest: ~/butane

- name: Copy butane binary with owner and permissions to /usr/local/bin
  ansible.builtin.copy:
    src: ~/butane
    dest: /usr/local/bin/butane
    owner: root
    group: root
    mode: '0755'

- name: Remove file ~/butane 
  ansible.builtin.file:
    path: ~/butane
    state: absent
