# source: https://cloud.google.com/sdk/docs/install#deb
---
- name: Install package dependencies.
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ca-certificates
    - curl
    - gnupg
    - apt-transport-https

- name: Add an apt signing key for google-cloud-cli
  become: true
  changed_when: false
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /etc/apt/keyrings/cloud.google.asc
    mode: '0644'
    force: true

- name: Add apt repository for stable version
  become: true
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/cloud.google.asc] https://packages.cloud.google.com/apt cloud-sdk main"
    state: present

- name: Install google-cloud-cli
  become: true
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - google-cloud-cli
