---
- name: Add an apt signing key for Helm
  become: true
  changed_when: false
  ansible.builtin.get_url:
    url: https://baltocdn.com/helm/signing.asc
    dest: /etc/apt/trusted.gpg.d/helm.asc
    mode: '0644'
    force: true

- name: Add apt repository for Helm
  become: true
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/helm.asc] https://baltocdn.com/helm/stable/debian/ all main"
    state: present
    filename: helm-stable-debian

- name: Install helm
  become: true
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - helm
