---
- name: Remove file ~/oc-mirror.tar.gz in case a of previously erroneous ansible runs
  ansible.builtin.file:
    path: ~/oc-mirror.tar.gz
    state: absent

- name: Download oc client tool for latest OpenShift Version 
  ansible.builtin.get_url:
    url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/oc-mirror.tar.gz"
    dest: ~/oc-mirror.tar.gz
  register: oc_mirror_download_bundle

- name: Extract oc-linux.tar.gz into ~/
  when: oc_mirror_download_bundle.changed
  ansible.builtin.unarchive:
    src: ~/oc-mirror.tar.gz
    dest: /usr/local/bin

- name: Remove file ~/oc-mirror.tar.gz 
  when: oc_mirror_download_bundle.changed
  ansible.builtin.file:
    path: ~/oc-mirror.tar.gz
    state: absent
