---
- name: Install package dependencies.
  package: name={{ item }} state=present
  with_items:
    - python3
    - python3-pip

- name: Install Molecule
  become: yes
  pip:
    name: molecule
