---
name: CI
'on':   # Single quotes for yamllint
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:   # Schedule for every 15th of a month at 5AM
    - cron: '0 5 15 * *'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.10.12'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible ansible-lint

      - name: Lint code with yamllint.
        run: |
          yamllint .

#      - name: Lint code with ansible-lint.
#        run: |
#          ansible-lint

  integration:
    name: Integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          # - ubuntu-20.04

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Run bootstrap script.
        run: ./bootstrap.sh

      - name: Test the playbook's syntax.
        run: ansible-playbook playbook.yaml --syntax-check

#      - name: Test the playbook.
#        run: ansible-playbook playbook.yaml
#        env:
#          ANSIBLE_FORCE_COLOR: '1'
