name: Molecule CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule: # Schedule for every 15th of a month at 5AM
    - cron: '0 5 15 * *'

jobs:
  test:
    name: Molecule
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        distro:
#          - rockylinux8
#          - debian10

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.10.12'

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] yamllint ansible-lint

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
#          MOLECULE_DISTRO: ${{ matrix.distro }}
        working-directory: ./
